# Generated by Django 5.2 on 2025-04-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='banners/')),
                ('link_url', models.URLField(blank=True, help_text='URL to link to when banner is clicked', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã giảm giá (ví dụ: SUMMER20)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_percentage', models.FloatField(blank=True, help_text='Tỷ lệ giảm giá (ví dụ: 10 cho 10%)', null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Số tiền giảm giá cố định (VNĐ)', max_digits=10, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('coming_soon', 'Sắp chiếu'), ('now_showing', 'Đang chiếu'), ('archived', 'Ngừng chiếu')], default='coming_soon', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
