# Generated by Django 5.2 on 2025-04-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_banner_faq_promotion_movie_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='status',
            field=models.CharField(choices=[('active', 'Đang hoạt động'), ('maintenance', 'Đang bảo trì'), ('closed', 'Ngừng hoạt động')], default='active', max_length=20),
        ),
    ]
