# Generated by Django 5.2 on 2025-04-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_theater_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seats',
            field=models.ManyToManyField(related_name='tickets', to='tickets.seat'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('used', 'Đã sử dụng'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
