# Generated by Django 5.2 on 2025-04-29 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticket_seat_ticket_seats_alter_ticket_status'),
        ('tickets', 'reset_sequence'),
    ]

    operations = [
    ]
