# Generated by Django 5.2 on 2025-04-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_id'),
        ('tickets', '0005_merge_20250429_1150'),
    ]

    operations = [
    ]
