# Generated by Django 5.2 on 2025-04-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_merge_0005_alter_ticket_id_0005_merge_20250429_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
